### ISSUE TITLE
希望支持AdvancedSlimePaper

### ISSUE THREAD

**Issue by inrhor** [Xiao-MoMi/Custom-Crops#29]
https://github.com/InfernalSuite/AdvancedSlimePaper

**Comment by Xiao-MoMi** [comment]
https://github.com/Xiao-MoMi/Custom-Crops/blob/main/plugin/src/main/java/net/momirealms/customcrops/mechanic/world/adaptor/SlimeWorldAdaptor.java

**Comment by inrhor** [comment]
@Xiao-MoMi 
我以为没支持，不过我需要反馈一下BUG，我在史莱姆世界种植并使用洒水器
在卸载史莱姆世界的时候，发生错误
```
[10:30:56 ERROR]: Could not pass event WorldUnloadEvent to CustomCrops v3.4.9
java.lang.NullPointerException: Cannot invoke "net.momirealms.customcrops.api.mechanic.world.level.CustomCropsRegion.saveChunk(net.momirealms.customcrops.api.mechanic.world.ChunkPos, byte[])" because "customCropsRegion" is null
        at net.momirealms.customcrops.mechanic.world.adaptor.BukkitWorldAdaptor.saveChunkToCachedRegion(BukkitWorldAdaptor.java:249) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.SlimeWorldAdaptor.saveChunkToCachedRegion(SlimeWorldAdaptor.java:165) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.WorldManagerImpl.saveChunkToCachedRegion(WorldManagerImpl.java:549) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.CWorld.save(CWorld.java:86) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.BukkitWorldAdaptor.unload(BukkitWorldAdaptor.java:80) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.SlimeWorldAdaptor.unload(SlimeWorldAdaptor.java:90) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.WorldManagerImpl.unloadWorld(WorldManagerImpl.java:187) ~[CustomCrops-plugin-3.4.9.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.BukkitWorldAdaptor.onWorldUnload(BukkitWorldAdaptor.java:277) ~[CustomCrops-plugin-3.4.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor139.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.unloadWorld(CraftServer.java:1414) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at org.bukkit.Bukkit.unloadWorld(Bukkit.java:833) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.grinderwolf.swm.plugin.commands.sub.UnloadWorldCmd.onCommand(UnloadWorldCmd.java:93) ~[plugin-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.grinderwolf.swm.plugin.commands.CommandManager.onCommand(CommandManager.java:83) ~[plugin-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[slimeworldmanager-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:1005) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[slimeworldmanager-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:338) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2279) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2239) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[slimeworldmanager-1.20.2.jar:git-SlimeWorldManager-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by inrhor** [comment]
使用洒水器的时候还有一个错误：
```
[10:30:47 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[10:30:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[10:30:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:315)
[10:30:47 WARN]:        at CustomCrops-plugin-3.4.9.jar//net.momirealms.customcrops.util.FakeEntityUtils.getDestroyPacket(FakeEntityUtils.java:46)
[10:30:47 WARN]:        at CustomCrops-plugin-3.4.9.jar//net.momirealms.customcrops.mechanic.misc.TempFakeItem.lambda$start$0(TempFakeItem.java:68)
[10:30:47 WARN]:        at CustomCrops-plugin-3.4.9.jar//net.momirealms.customcrops.scheduler.SchedulerImpl.lambda$runTaskAsyncLater$0(SchedulerImpl.java:95)
[10:30:47 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[10:30:47 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[10:30:47 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[10:30:47 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:30:47 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:30:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Xiao-MoMi** [comment]
问题1：
https://github.com/Xiao-MoMi/Custom-Crops/blob/main/plugin/src/main/java/net/momirealms/customcrops/mechanic/world/adaptor/SlimeWorldAdaptor.java#L164
根据你的描述，史莱姆世界被卸载触发此问题，但是这里判断了世界是否为史莱姆世界。也就是说你的史莱姆世界并没有在WorldUnloadEvent的时候被判断为史莱姆世界，最终使用了Bukkit世界适配器进行了区块卸载导致错误。

我测试的时候使用asp1.20.4，并未出现所示的问题
根据asp的代码可知
https://github.com/InfernalSuite/AdvancedSlimePaper/blob/dc112775adc988eac54444a215ab055a41a538f9/plugin/src/main/java/com/grinderwolf/swm/plugin/SWMPlugin.java#L310
只有在世界卸载触发后，才会从map移除对应的史莱姆世界

https://github.com/InfernalSuite/AdvancedSlimePaper/blob/dc112775adc988eac54444a215ab055a41a538f9/plugin/src/main/java/com/grinderwolf/swm/plugin/SWMPlugin.java#L266
农作物在世界卸载世界期间获取史莱姆世界实例不应该为null，所以可能是事件优先级导致的问题。你那边有1.20.2的环境，可以尝试修改一下事件优先级看看是否可以修复

问题2：
因为插件只支持1.17+所以向来都是写入的List<Integer>，可能是你的protocollib版本问题
https://github.com/Xiao-MoMi/Custom-Crops/blob/main/plugin/src/main/java/net/momirealms/customcrops/util/FakeEntityUtils.java#L44
