### ISSUE TITLE
Error occurring when saving worlds with SlimeWorldManager

### ISSUE THREAD

**Issue by minhyeok1202** [Xiao-MoMi/Custom-Crops#30]
[15:11:10 ERROR]: Could not pass event WorldUnloadEvent to CustomCrops v3.4.7
java.lang.NullPointerException: Cannot invoke "net.momirealms.customcrops.api.mechanic.world.level.CustomCropsRegion.saveChunk(net.momirealms.customcrops.api.mechanic.world.ChunkPos, byte[])" because "customCropsRegion" is null
        at net.momirealms.customcrops.mechanic.world.adaptor.BukkitWorldAdaptor.saveChunkToCachedRegion(BukkitWorldAdaptor.java:249) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.SlimeWorldAdaptor.saveChunkToCachedRegion(SlimeWorldAdaptor.java:165) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.WorldManagerImpl.saveChunkToCachedRegion(WorldManagerImpl.java:549) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.CWorld.save(CWorld.java:86) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.BukkitWorldAdaptor.unload(BukkitWorldAdaptor.java:80) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.SlimeWorldAdaptor.unload(SlimeWorldAdaptor.java:90) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.WorldManagerImpl.unloadWorld(WorldManagerImpl.java:187) ~[CustomCrops-3.4.7.jar:?]
        at net.momirealms.customcrops.mechanic.world.adaptor.BukkitWorldAdaptor.onWorldUnload(BukkitWorldAdaptor.java:277) ~[CustomCrops-3.4.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor485.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.unloadWorld(CraftServer.java:1463) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at org.bukkit.Bukkit.unloadWorld(Bukkit.java:863) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.flow.xlands.bukkit.hook.WorldSmileHook.lambda$slimeWorldUnLoad$13(WorldSmileHook.java:290) ~[xLands-1.0.jar:?]
        at com.flow.xlands.bukkit.BukkitInitializer$1.run(BukkitInitializer.java:110) ~[xLands-1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1694) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1573) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-43]
        at java.lang.Thread.run(Thread.java:1595) ~[?:?]
[15:11:10 INFO]: Saving world 6bfbb791-a2dd-42cc-89f6-a12712cb619b...

An error like the one mentioned occurs when unloading worlds created with SlimeWorldManager.

**Comment by Xiao-MoMi** [comment]
Probably fixed that in next release
